In [1]:
import numpy as np

In [2]:
a = [1, 3.14, True, 'hello']
b = np.array(a)

In [3]:
print(a)
for element in a : 
    print('Data type of {} : {}'.format(element, type(element)))

[1, 3.14, True, 'hello']
Data type of 1 : <class 'int'>
Data type of 3.14 : <class 'float'>
Data type of True : <class 'bool'>
Data type of hello : <class 'str'>


In [4]:
print(b)
for element in b : 
    print('Data type of {} : {}'.format(element, type(element)))

['1' '3.14' 'True' 'hello']
Data type of 1 : <class 'numpy.str_'>
Data type of 3.14 : <class 'numpy.str_'>
Data type of True : <class 'numpy.str_'>
Data type of hello : <class 'numpy.str_'>


In [5]:
a = [[1,2,3],[4,5,6]]

In [6]:
print(a)

[[1, 2, 3], [4, 5, 6]]


In [7]:
type(a)

list

In [8]:
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [9]:
type(b)

numpy.ndarray

In [10]:
b.shape

(2, 3)

In [11]:
b.ndim

2

In [12]:
b.size

6

In [13]:
print(b.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [14]:
#단순하게 reshpae 메소드를 호출하면 된다.

In [15]:
b = np.array(a, dtype=np.float64)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
b = b.astype(np.int64)
print(b)

[[1 2 3]
 [4 5 6]]


In [17]:
arr = np.array([1,2,3,4,5])

In [18]:
print(arr)

[1 2 3 4 5]


In [19]:
print(arr[0])

1


In [20]:
print(arr[3])

4


In [21]:
print(arr[-1])

5


In [22]:
arr_2d = np.array([1,2,3],[4,5,6])

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [23]:
arr_2d = np.array([[1,2,3],[4,5,6]])

In [24]:
arr_2d[0,0]

1

In [25]:
arr_2d[1,2]

6

In [26]:
arr_2d = np.arange(1,7).reshape(2,3)

In [27]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [28]:
print(arr_2d[0,:])

[1 2 3]


In [29]:
print(arr_2d[1:])

[[4 5 6]]


In [30]:
print(arr_2d[:,2])

[3 6]


In [31]:
print(arr_2d[:,:2])

[[1 2]
 [4 5]]


In [32]:
import pandas as pd

In [33]:
data = {
    '이름' : ['아이유','김연아','홍길동','장범준','강감찬'],
}

In [34]:
data = {
    '이름' : ['아이유','김연아','홍길동','장범준','강감찬'],
    '학과' : ['국문학','수학','컴퓨터','철학','경영학'],
    '성적' : [3.0,1.9,3.5,2.7,4.0]
}

In [35]:
data

{'이름': ['아이유', '김연아', '홍길동', '장범준', '강감찬'],
 '학과': ['국문학', '수학', '컴퓨터', '철학', '경영학'],
 '성적': [3.0, 1.9, 3.5, 2.7, 4.0]}

In [36]:
df = pd.DataFrame(data)

display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.9
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [39]:
df.to_csv('./data/student.csv',sep=',',index=False)

In [40]:
df = pd.read_csv('./data/student.csv')
display(df)

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.9
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [41]:
df[1:5]

이름   학과   성적
1  김연아   수학  1.9
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [42]:
df[0:3]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.9
2  홍길동  컴퓨터  3.5

In [43]:
df[0:]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.9
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [44]:
df[:]

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.9
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [45]:
df[1]

KeyError: 1

In [46]:
df['이름']

0    아이유
1    김연아
2    홍길동
3    장범준
4    강감찬
Name: 이름, dtype: object

In [47]:
df['학과']

0    국문학
1     수학
2    컴퓨터
3     철학
4    경영학
Name: 학과, dtype: object

In [48]:
df[['이름','학과']]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

In [49]:
fancy_list = ['이름','학과']

In [50]:
df [fancy_list]

이름   학과
0  아이유  국문학
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학
4  강감찬  경영학

In [51]:
df[1:3][['학과','이름']]

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

In [52]:
df[['학과','이름']][1:3]

학과   이름
1   수학  김연아
2  컴퓨터  홍길동

In [53]:
df [ df['학과'] == '수학']

이름  학과   성적
1  김연아  수학  1.9

In [54]:
df

이름   학과   성적
0  아이유  국문학  3.0
1  김연아   수학  1.9
2  홍길동  컴퓨터  3.5
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [55]:
df [df['학과'] == '철학']

이름  학과   성적
3  장범준  철학  2.7

In [56]:
df[df['성적'] % 0.5 == 0]

이름   학과   성적
0  아이유  국문학  3.0
2  홍길동  컴퓨터  3.5
4  강감찬  경영학  4.0

In [57]:
df['성적'] % 0.5 == 0

0     True
1    False
2     True
3    False
4     True
Name: 성적, dtype: bool

In [58]:
df.loc[3]

이름    장범준
학과     철학
성적    2.7
Name: 3, dtype: object

In [61]:
type(df.loc[3])

pandas.core.series.Series

In [62]:
df.loc[[1,3,4]]

이름   학과   성적
1  김연아   수학  1.9
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [63]:
df.loc[[1,3,4]]

이름   학과   성적
1  김연아   수학  1.9
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [64]:
df.loc[[1,3,4],:]

이름   학과   성적
1  김연아   수학  1.9
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [69]:
df.loc[ [1,3,4], '이름' : '학과']

이름   학과
1  김연아   수학
3  장범준   철학
4  강감찬  경영학

In [73]:
df.loc[[1,2,3],'이름' : '학과']

이름   학과
1  김연아   수학
2  홍길동  컴퓨터
3  장범준   철학

In [75]:
df.iloc[[1,3,4],0:3]

이름   학과   성적
1  김연아   수학  1.9
3  장범준   철학  2.7
4  강감찬  경영학  4.0

In [79]:
df.loc[df['성적'] % 2 != 0 , ['이름':'성적']]

SyntaxError: invalid syntax (141359392.py, line 1)